from retained_diagnostic_metadata import metadata as retained_metadata
"""Continuation scope and independent display oracles; invented masks only."""
from copy import deepcopy
import json
import io
import numpy as np
import pytest
from PIL import Image
from scripts.diagnostics import segmenter_content_continuation as runner
from scripts.diagnostics import segmenter_content_pilot as pilot
from src.data import segmenter_native_views_v2 as views
from src.data import segmenter_content_v1 as core


@pytest.mark.parametrize('fault',['none','role','duplicate','omit','extra','kind','substitute','bytes','expanded','identity'])
def test_continuation_scope_rejects_changed_inputs(fault):
    rows=retained_metadata()['continuation']['files']
    rows=deepcopy(rows)
    if fault=='role':rows[0]['protected_role']='validation'
    elif fault=='duplicate':rows[1]=deepcopy(rows[0])
    elif fault=='omit':rows.pop()
    elif fault=='extra':rows.append(deepcopy(rows[0]))
    elif fault=='kind':rows[0]['kind']='lesion'
    elif fault=='substitute':rows[0]['study_id']='pants:study:PanTS_00000003'
    elif fault=='bytes':rows[0]['compressed_bytes']+=1
    elif fault=='expanded':rows[0]['expanded_bytes']+=1
    elif fault=='identity':rows[0]['study_id']='other:study:PanTS_00006110'
    if fault=='none':runner.validate_scope(rows)
    else:
        with pytest.raises(ValueError):runner.validate_scope(rows)


@pytest.mark.parametrize('fault',['wrong_role','extra_file','changed_code','changed_cap','changed_hash','changed_geometry','changed_budget','changed_runtime'])
def test_frozen_request_mutation_refused_before_claim(tmp_path,monkeypatch,fault):
    dest=tmp_path/'fixed';dest.mkdir();path=dest/'request.json'
    good=dict(profile_receipt_sha256='invented',files=[dict(role='train',sha256='original',geometry={'shape':[3,4,5]})],
              code_pins={'source':'original'},runtime={'python':'original'},capability={'source_writes':False},limits={'seconds':900})
    bad=deepcopy(good)
    if fault=='wrong_role':bad['files'][0]['role']='test'
    elif fault=='extra_file':bad['files'].append(deepcopy(bad['files'][0]))
    elif fault=='changed_code':bad['code_pins']['source']='other'
    elif fault=='changed_cap':bad['capability']['source_writes']=True
    elif fault=='changed_hash':bad['files'][0]['sha256']='other'
    elif fault=='changed_geometry':bad['files'][0]['geometry']['shape'][0]=9
    elif fault=='changed_budget':bad['limits']['seconds']=901
    elif fault=='changed_runtime':bad['runtime']['python']='other'
    monkeypatch.setattr(runner,'DEST',dest);monkeypatch.setattr(runner,'build_request',lambda _:good)
    runner.source.put(path,bad)
    with pytest.raises(ValueError):runner.checked_request(path,runner.source.sha(path.read_bytes()))
    assert not (dest/'consumed.json').exists()


def test_empty_context_has_no_duplicate_or_fictitious_detail(monkeypatch):
    labels=[];original=views.ImageDraw.ImageDraw.text
    def capture(self,xy,text,*a,**k):labels.append(text);return original(self,xy,text,*a,**k)
    monkeypatch.setattr(views.ImageDraw.ImageDraw,'text',capture)
    shape=(3,4,5);ct=np.zeros(shape);pan=np.ones(shape,np.uint8);les=np.zeros(shape,np.uint8)
    png,r=views.render_native(ct,pan,les,np.eye(4),'empty',[])
    assert len(r['panels'])==3 and all(p['view_kind']=='context' and not p['detail'] and p['detail_box'] is None for p in r['panels'])
    assert Image.open(io.BytesIO(png)).size==(1440,500)
    assert any('not verified negative' in s for s in labels) and not any('native detail' in s for s in labels)
    assert np.all(pan==1) and not les.any()


def test_new_display_preserves_independent_world_oracle():
    a=np.array([[0,0,-3,30],[-2,0,0,8],[0,4,0,-12],[0,0,0,1]],float)
    ct=np.zeros((4,5,6));pan=np.ones_like(ct,np.uint8);les=np.zeros_like(ct,np.uint8);les[1,2,4]=1
    metrics=core.component_content(les,pan,a);_,r=views.render_native(ct,pan,les,a,'tiny',metrics['components'])
    point=np.array([1,2,4,1]);ras=np.array(r['native_to_ras_voxel_affine'])@point
    assert np.array_equal(ras,[1,2,2,1]) and np.allclose(np.array(r['ras_affine'])@ras,a@point)
    assert any(p['view_kind']=='detail' and p['detail_box'] for p in r['panels']) and les.sum()==1


def test_old_pilot_scope_stays_fixed():
    assert len(pilot.PILOT)==4 and set(pilot.PILOT).isdisjoint(runner.CASES)
    assert pilot.DEST!=runner.DEST and pilot.PROFILE!=runner.PROFILE and len(runner.CASES)==8
    # The original bytes are evidence, not regenerated by this continuation.
    assert runner.source.sha((runner.REPO/'scripts/diagnostics/segmenter_content_pilot.py').read_bytes())=='433913a3efa75ac686fccaef9f3c3c1a19137a12f4df280f8d620092c5ed602e'
