import { test, expect } from '@playwright/test'

test('real fixture API saves, reloads, refuses diagnosis and preserves viewer on failure', async ({ page, request }, testInfo) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('https://fonts.googleapis.com/**', route => route.fulfill({ contentType: 'text/css', body: '' }))
  await page.goto('/')
  await page.getByText('Guided evidence questions', { exact: false }).click()
  await page.getByRole('button', { name: 'Ask and save fixture response' }).click()
  await expect(page.getByRole('heading', { name: 'Supported by the selected fixture' })).toBeVisible()
  const link = page.getByRole('link', { name: 'Download saved response JSON' })
  const artifactUrl = await link.getAttribute('href')
  const saved = await (await request.get(artifactUrl)).json()
  expect(saved.state).toBe('answered')
  expect(saved.claims[0].text).toBe(saved.citations[0].text)
  // Retry after save returns the same durable artifact, including original completion time.
  const retry = await request.post('/evidence-fixture/responses', { data: saved.request })
  expect(await retry.json()).toEqual(saved)
  await page.getByText('Supporting passage: Synthetic reviewer workflow').click()
  for (const [width, height] of [[1280, 720], [1024, 768]]) {
    await page.setViewportSize({ width, height })
    await link.scrollIntoViewIfNeeded()
    await expect(link).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath(`guided-${width}.png`), fullPage: true })
  }
  await page.getByLabel('Reviewer question').selectOption('diagnosis-boundary')
  await page.getByRole('button', { name: 'Ask and save fixture response' }).click()
  await expect(page.getByRole('heading', { name: 'Outside PROWL’s scope' })).toBeVisible()
  await expect(page.getByText('Supporting passage: Synthetic reviewer workflow')).toHaveCount(0)
  await page.getByLabel('Reviewer question').selectOption('measurement')
  await page.getByRole('button', { name: 'Ask and save fixture response' }).click()
  await expect(page.getByRole('heading', { name: 'Not enough evidence' })).toBeVisible()
  await page.route('**/evidence-fixture/responses', route => route.fulfill({ status: 503, body: '{}' }))
  await page.getByRole('button', { name: 'Ask and save fixture response' }).click()
  await expect(page.getByRole('alert')).toContainText('A saved response could not be confirmed')
  await expect(page.getByRole('link', { name: 'Download saved response JSON' })).toHaveCount(0)
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await expect(page.getByRole('button', { name: '3D', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Switch synthetic case' }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.reload()
  expect(await (await request.get(artifactUrl)).json()).toEqual(saved)
  expect(errors).toEqual([])
})
